# Config file dedicated to the user's personal zshrc profile shared between all exegol containers.
# This file is sourced in /root/.zshrc file.
# Alternatively, the /opt/my-resources/setup/load_user_setup.sh file can be used to operate the change once (instead of sourcing a file for each zsh instance)

expand_alias(){
    LBUFFER=$(/opt/my-resources/bin/expand-alias "$BUFFER")
}
zle -N expand_alias
bindkey '^\' expand_alias

fakeclock() {
  faketime "$(rdate -n ${1:-$DC_IP} -p | awk '{print $2, $3, $4}' | date -f - "+%Y-%m-%d %H:%M:%S")" zsh
}

alias unhex="pwn unhex"
alias f="htb submit"